#!/bin/bash

has(){
	type ${1} > /dev/null 2>&1
	return $?
}

error(){
	echo "${1}"
	return 1
}

has "gsed" || error "gsed not installed"
has "git" || error "git not installed"
has "gh" || error "gh not installed"
